### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-matchers#16]
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment]
this task will get someone's attention soon

**Comment by dmarkov** [comment]
@palyuga this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here... The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmarkov** [comment]
@maurezen thanks for tis bug, I topped your account for 15 mins, transaction `50303596`

**Comment by palyuga** [comment]
@maurezen PR is merged. Close, please.

**Comment by dmarkov** [comment]
@palyuga Much obliged! I've added **30 mins** to your account in payment "50572788"; +30 added to your rating, at the moment it is: +120
